name: gpr-publish
on:
  push:
    branches: [ v1 ]
jobs:
  gpr-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm i
      - run: npm run pkg:build
      - run: npm run pkg:upload
#       - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
